### PR TITLE
docs(changelog): add layer list changes

### PR DESCRIPTION
**Pull request by sagewall**
- adds an topic and a breaking change to the changelog for the LayerList calcite refactor

### CODE REVIEW

**Comment by sagewall** [comment]
@bsvensson got time to review?

**Comment by sagewall** [comment]
We should wait to merge this until some of the properties have been renamed.

**Comment by sagewall** [comment]
I think this is good place to merge, @annelfitz could you please review?

**Review by annelfitz — APPROVED** [review]
LGTM!

**Pull request merged**
